/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.sql.SQLOutput;
import java.util.*;
import java.util.function.Predicate;
import java.util.stream.Collectors;

public class App {
    public static void main(String[] args) {
//        List<Integer> l = Arrays.asList(1,2,3,4,5);
//        List<Integer> l1 = l.stream().filter(e->e%2==0).toList();
//        List<Integer> l2 = l.stream().map(e->e*2).toList();
        System.out.println("Running Train Booking system");
        Scanner scanner=new Scanner(System.in);
        int option=0;
        int selectedTrain = -1;
        Train selectedTrainForBooking = null;
        UserBookingService userBookingService;
        String src=null,dest=null;
        try{
            userBookingService=new UserBookingService();
        }catch (IOException ex){
            ex.printStackTrace();
            return;
        }

        while(option!=7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();
            switch (option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = scanner.next();
                    User userToSignup = new User(nameToSignUp, passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignup);
                    break;
                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter the password to Login");
                    String passwordToLogin = scanner.next();
                    User userToLogin = new User();
                    userToLogin.setName(nameToLogin);
                    userToLogin.setPassword(passwordToLogin);
                    try{
                        userBookingService = new UserBookingService(userToLogin);
                        if(!userBookingService.loginUser()){
                            System.out.println("Invalid login credentials");
                            return;
                        }
                    }catch(IOException ex){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    src = scanner.next();
                    System.out.println("Type your destination station");
                    dest = scanner.next();
                    List<Train> trains = UserBookingService.getTrains(src,dest);
                    int index=1;
                    for(Train t: trains){
                        System.out.println(index + ". Train id: "+t.getTrainId());
                        for(Map.Entry<String,String> entry:t.getStationTimes().entrySet()){
                            System.out.println("Station "+entry.getKey()+" time: "+entry.getValue());
                        }
                        index++;
                    }

                    System.out.println("Select a train by typing 1,2,3,...");
                    selectedTrain = scanner.nextInt();
                    if(selectedTrain>=1 && selectedTrain<= trains.size()) {
                        selectedTrainForBooking = trains.get(selectedTrain - 1);
                    }else selectedTrain = -1;
                    break;
                case 5:
                    if(selectedTrain!=-1){
                        List<List<Integer>> seats = selectedTrainForBooking.getSeats();
                        System.out.println("Select a seat out of the available seats");

                        for(List<Integer> row:seats){
                            for(Integer val:row){
                                System.out.print(val+" ");
                            }
                            System.out.println();
                        }

                        System.out.println("Select a seat by tying row and col");
                        System.out.println("Enter row: ");
                        int row = scanner.nextInt();
                        System.out.println("Enter col: ");
                        int col = scanner.nextInt();

                        System.out.println("Enter dateOfTravel: ");
                        String dateOfTravel = scanner.next();

                        System.out.println("Booking your seat...");
                        Boolean booked = userBookingService.bookTrainSeat(selectedTrainForBooking,src,dest,dateOfTravel,row,col);
                        if(booked.equals(Boolean.TRUE)){
                            System.out.println("Booked! Enjoy your journey.");
                        }else{
                            System.out.println("Can't book this seat...");
                        }
                    }else{
                        System.out.println("No train selected for booking");
                    }
                    selectedTrain = -1;
                    selectedTrainForBooking = null;
                    break;
                case 6:
                    System.out.println("Enter the ticket id for the ticket to delete: ");
                    String ticketId = scanner.next();
                    try{
                        if(userBookingService.cancelBooking(ticketId)){
                            System.out.println("Booking successfully cancelled");
                        }else {
                            System.out.println("Not able to cancel booking for requested ticket id");
                        }
                    }catch(IOException ex){
                        System.out.println("Not able to cancel booking for requested ticket id");
                    }
                default:
                    break;

            }
        }
}
}
